version: '3'

services:
  movie_recommender:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MOVIES_FILE_PATH=/app/movie_recommender/data/movielens/movies.csv
      - CLEANED_RATINGS_FILE_PATH=/app/movie_recommender/data/process/cleaned_ratings.csv
