version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      MOVIES_FILE_PATH: "/app/data/movielens/movies.csv"
      CLEANED_RATINGS_FILE_PATH: "/app/data/process/cleaned_ratings.csv"
