name: Docker Integration Tests
on:
  push:
    branches: [ "**" ]

  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30s

      - name: Run integration test
        run: docker-compose run recommendation-services python tests/integration/test_api.py

      - name: Stop containers
        run: docker-compose down